[package]
name = "konnektoren"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]
path = "src/lib.rs"

[[bin]]
name = "konnektoren-pwa"
path = "src/main.rs"

[dependencies]
base64 = "0.22.0"
charts-rs = "0.3.3"
rand = "0.8"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_yaml = "0.8"
wasm-bindgen = "0.2"
web-sys = { version = "0.3.*", features = [
    "HtmlTextAreaElement",
    "HtmlSelectElement",
] }
yew = { version = "0.21.0", features = ["csr"] }
yew-bootstrap = "0.10.0"
yew-router = "0.18.0"
