[package]
name = "konnektoren"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]
path = "src/lib.rs"

[[bin]]
name = "konnektoren-pwa"
path = "src/main.rs"

[dependencies]
base64 = "0.22.0"
charts-rs = "0.3.4"
ed25519-dalek = "2.1"
gloo-timers = "0.3"
image = "0.24"
imageproc = "0.23"
rand = "0.8"
sha2 = "0.9"
qrcode = "0.13.0"
rusttype = "0.9.3"
serde = { version = "1.0", features = ["derive"] }
serde_cbor = "0.11.2"
serde_json = "1.0"
serde_yaml = "0.8"
urlencoding = "2.1.3"
wasm-bindgen = "0.2"
web-sys = { version = "0.3.*", features = [
    "HtmlTextAreaElement",
    "HtmlSelectElement",
    "Window",
] }
yew = { version = "0.21.0", features = ["csr"] }
yew-bootstrap = "0.10.0"
yew-router = "0.18.0"
yew-hooks = "0.3.1"
