[package]
name = "konnektoren"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.8"
wasm-bindgen = "0.2.*"
web-sys = { version = "0.3.*", features = [
    "HtmlTextAreaElement",
    "HtmlSelectElement",
] }
yew = { version = "0.21.0", features = ["csr"] }
yew-bootstrap = "0.10.0"

[dev-dependencies]
serde_json = "1.0"
