[package]
name = "worker-rust"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
worker = "0.0.21"
konnektoren = { git="https://github.com/SofiiaVarich/konnektoren.git", default-features = false }
image = "0.24"
getrandom = {version = "0.2", features = ["js"] }

[profile.release]
opt-level = "s"
lto = true
strip = true
codegen-units = 1
