[package]
name = "konnektoren-worker-rust"
description = "Konnektoren Worker Rust"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
anyhow = "1.0.81"
getrandom = { version = "0.2", features = ["js"] }
konnektoren = { git = "https://github.com/SofiiaVarich/konnektoren.git", default-features = false, features = [
    "certificate-image",
] }
image = "0.24"
urlencoding = "2.1.3"
worker = "0.0.21"

[profile.release]
opt-level = "s"
lto = true
strip = true
codegen-units = 1
