mod adjective_detail;
mod adjective_type;
mod adjectives;
mod answer_record;
mod categorized_items;
mod categorized_test;
mod category;
mod detail_trait;
mod konnektor_detail;
mod konnektor_type;
mod nomen_detail;
mod nomen_type;
mod player;
mod test_result;
mod test_type;
mod type_trait;
mod verb_detail;
mod verb_type;

pub use adjective_detail::AdjectiveDetail;
pub use adjective_type::AdjectiveType;
pub use adjectives::Adjectives;
pub use answer_record::AnswerRecord;
pub use categorized_items::CategorizedItems;
pub use categorized_test::CategorizedTest;
pub use category::Category;
pub use detail_trait::DetailTrait;
pub use konnektor_detail::KonnektorDetail;
pub use konnektor_type::KonnektorType;
pub use nomen_detail::NomenDetail;
pub use nomen_type::NomenType;
pub use player::Player;
pub use test_result::TestResult;
pub use test_type::TestType;
pub use type_trait::TypeTrait;
pub use verb_detail::VerbDetail;
pub use verb_type::VerbType;
