mod about;
mod adjectives;
mod config;
mod history;
mod home;
mod konnektoren;
mod language_page;
mod leaderboard;
mod profile;
mod results;
mod survey;
mod verbs;

pub use about::About;
pub use adjectives::AdjectivesPage;
pub use config::ConfigPage;
pub use history::HistoryPage;
pub use home::Home;
pub use konnektoren::KonnektorenPage;
pub use language_page::LanguagePage;
pub use leaderboard::LeaderboardPage;
pub use profile::ProfilePage;
pub use results::Results;
pub use survey::Survey;
pub use verbs::VerbsPage;
