name: GitHub Pages

on:
  push:
    branches:
      - main
    tags:
      - "*"

jobs:
  build_and_deploy_main:
    name: Rust project for main branch
    runs-on: ubuntu-20.04
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: jetli/wasm-pack-action@v0.3.0
        with:
          version: "latest"

      - run: rustup target add wasm32-unknown-unknown
      - run: cargo install --locked trunk
      - run: trunk build --release

      - name: Generate Sitemap
        run: ./scripts/generate_sitemap.sh && cp ./sitemap.xml ./dist/sitemap.xml

      - name: Copy robots.txt
        run: cp ./robots.txt ./dist/robots.txt

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./dist
          keep_files: true
