name: GitHub Pages

on:
  push:
    branches:
      - main
    tags:
      - "*"

jobs:
  build_and_deploy_main:
    name: Rust project for main branch
    runs-on: ubuntu-22.04
    if: github.ref == 'refs/heads/main'
    env:
      SIGNATURE_PRIVATE_KEY: default_private_key
      #SIGNATURE_PRIVATE_KEY: ${{ secrets.SIGNATURE_PRIVATE_KEY }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: jetli/trunk-action@v0.5.0
        with:
          version: "latest"

      - run: rustup target add wasm32-unknown-unknown
      - run: trunk build --release

      - name: Generate Sitemap
        run: ./scripts/generate_sitemap.sh && cp ./sitemap.xml ./dist/sitemap.xml

      - name: Copy robots.txt
        run: cp ./robots.txt ./dist/robots.txt

      - name: Copy NFT Metadata
        run: cp ./nft-metadata.json ./dist/nft-metadata.json

      - name: Generate OpenApi
        run: cargo run --bin konnektoren-openapi --features=openapi && cp ./openapi.json ./dist/openapi.json

      - name: Generate DID Document
        run: mkdir -p ./dist/.well-known && cargo run --bin did_json -- konnektoren.help && cp ./did.json ./dist/.well-known/did.json

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./dist
          keep_files: true
